TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lm500.db
DATA += lm500.proto

#=======================================
include $(TOP)/configure/RULES
